FEEL ❤❤💕💕💕💕 : MINIMUM DISTACE WALE KO SABSE PAHLE UTHAO AND DEKHTE CHALE JAO KI KYA TUM KUCH BETTER CONTRIBUTION KAR SAKTE HO.....IF HAN THEN PROIRITY QUEUE ME DAL 
DO AND REPEAT THIS UNTILL THE PQ IS EMPTY
